## ebs_dynamic_sc.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-db-sc
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  allowAutoIOPSPerGBIncrease: 'true'
  encrypted: 'true'
  
# db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql

---
# db-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root12345
            - name: MYSQL_USER
              value: app
            - name: MYSQL_PASSWORD
              value: app12345
            - name: MYSQL_DATABASE
              value: app
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldata
  volumeClaimTemplates:
    - metadata:
        name: mysqldata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Mi
        storageClassName: ebs-db-sc
