apiVersion: v1
kind: Service
metadata:
  name: app-argocd-service
spec:
  selector:
    app.kubernetes.io/name: app-argocd-application
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31080
    port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-argocd-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-argocd-application
    spec:
      containers:
      - name: app-argocd-container
        image: 343218222789.dkr.ecr.ap-northeast-2.amazonaws.com/eks-app:95c41b4cdfcd9dce4b7551748f092554f82bdcf3
        ports:
          - protocol: TCP
            containerPort: 8080
