apiVersion: v1
kind: Service 
metadata:
  name: app-argocd-service
spec:
  selector:
    app.kubernetes.io/name: app-argocd-application
  type: NodePort
  ports:
  - protocol: TCP
    nodeport: 31080
    port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-argocd-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-argocd-application
    spec:
      containers:
      - name: app-argocd-container
        image: 343218222789.dkr.ecr.ap-northeast-2.amazonaws.com/eks-app:a5e1dc53a417bcbec84419a9b13d9b2b79f1b442
        ports:
          - protocol: TCP
            containerPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-argocd-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: application.cloud-route53-leeseoyoung.store
spec:
  rules:
  - host: application.cloud-route53-leeseoyoung.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-argocd-service
            port:
              number: 8080 
